workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean previous builds
        script: |
          flutter clean
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
      - name: Update CocoaPods repository
        script: |
          pod repo update
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install iOS dependencies with updated repo
        script: |
          cd ios && pod install --repo-update
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa 