workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.vote"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Clean previous builds
        script: |
          flutter clean
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
      - name: Update CocoaPods repository
        script: |
          pod repo update
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install iOS dependencies with updated repo
        script: |
          cd ios && pod install --repo-update
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      # App Store Connect publishing
      app_store_connect:
        auth: integration
        
        # Configuration for App Store Connect
        submit_to_testflight: false
        submit_to_app_store: false 