workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa 