// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnMmHhtqSXFKe37RQaa1TIpvGvrZ6Rjc',
    appId: '1:340312073242:web:b62d5fcc6e425f72661da3',
    messagingSenderId: '340312073242',
    projectId: 'vote-app1',
    authDomain: 'vote-app1.firebaseapp.com',
    storageBucket: 'vote-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7m1Ws2NdhihG4G4S-gnE5dNBtYt_2Lc',
    appId: '1:340312073242:android:1f98d42cd150b3fa661da3',
    messagingSenderId: '340312073242',
    projectId: 'vote-app1',
    storageBucket: 'vote-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyC9_sO8rKa4rPC97U6hnfV2Ski4vdN0',
    appId: '1:340312073242:ios:8f445b9a6da92305661da3',
    messagingSenderId: '340312073242',
    projectId: 'vote-app1',
    storageBucket: 'vote-app1.firebasestorage.app',
    iosBundleId: 'com.example.vote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXyC9_sO8rKa4rPC97U6hnfV2Ski4vdN0',
    appId: '1:340312073242:ios:8f445b9a6da92305661da3',
    messagingSenderId: '340312073242',
    projectId: 'vote-app1',
    storageBucket: 'vote-app1.firebasestorage.app',
    iosBundleId: 'com.example.vote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfnMmHhtqSXFKe37RQaa1TIpvGvrZ6Rjc',
    appId: '1:340312073242:web:6b8f5feb3ef1035d661da3',
    messagingSenderId: '340312073242',
    projectId: 'vote-app1',
    authDomain: 'vote-app1.firebaseapp.com',
    storageBucket: 'vote-app1.firebasestorage.app',
  );
}
